# Generated by Django 3.0.7 on 2020-06-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='noti_type',
            field=models.CharField(choices=[('RESPONSE', 'RESPONSE'), ('INFO', 'INFO'), ('OTHER', 'OTHER')], default='INFO', max_length=10),
        ),
    ]
