# Generated by Django 3.0.7 on 2020-07-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='object_id',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
