# Generated by Django 3.0.7 on 2020-06-22 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='parent_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='discussions.Question'),
        ),
    ]
