# Generated by Django 3.0.7 on 2020-06-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0003_auto_20200621_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='response',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
